# Generated by Django 4.2.4 on 2023-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('FLname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField(max_length=50)),
            ],
        ),
    ]
